### ISSUE TITLE
UAST spec: fixed values for roles

### ISSUE THREAD

**Issue by manucorporat** [bblfsh/documentation#62]
I think we should keep a binary compatibility with roles, ie, even if the list of roles changes in the future the associated numeric number will not.

I propose to change:

```
const (
    // Invalid Role is assigned as a zero value since protobuf enum definition must start at 0.
    Invalid Role
    SimpleIdentifier
    QualifiedIdentifier
    BinaryExpression
    BinaryExpressionLeft
    BinaryExpressionRight
    BinaryExpressionOp
    /// ...
```

to: 
```
const (
    // Invalid Role is assigned as a zero value since protobuf enum definition must start at 0.
    Invalid Role = 0
    SimpleIdentifier = 1
    QualifiedIdentifier = 2
    BinaryExpression = 3
    BinaryExpressionLeft = 4
    BinaryExpressionRight = 5
    BinaryExpressionOp = 6
    /// ...
```
https://godoc.org/github.com/bblfsh/sdk/uast#Role

This is specially important since we will need to provide these roles in the C++ library too.

**Comment by abeaumont** [comment]
This should go to the sdk repo I think. They currently have a number though, otherwise it wouldn't work with current clients either. We should probably consider breaking compatibility with major versions only, but at this point we're not even 1.0, so backwards compatibility is not expected (but we take of it anyway not to break everything).

**Comment by abeaumont** [comment]
We are going to add versioning to UAST, so closing this.
